// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aplicationProject.Models;

namespace aplicationProject.Migrations
{
    [DbContext(typeof(UsersReviewingMoviesContext))]
    [Migration("20180711090229_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("aplicationProject.Models.Movie", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("Likes");

                    b.Property<string>("Name");

                    b.Property<byte[]>("Poster");

                    b.Property<DateTime>("Release");

                    b.HasKey("MovieID");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("aplicationProject.Models.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime>("Publish");

                    b.Property<string>("UserName");

                    b.HasKey("ReviewID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("aplicationProject.Models.Reviewing", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MovieID");

                    b.Property<int>("ReviewID");

                    b.HasKey("ID");

                    b.HasIndex("MovieID");

                    b.HasIndex("ReviewID");

                    b.ToTable("Reviewings");
                });

            modelBuilder.Entity("aplicationProject.Models.User", b =>
                {
                    b.Property<string>("UserName")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MyProperty");

                    b.Property<string>("Name");

                    b.Property<string>("PassWord");

                    b.Property<DateTime>("Register");

                    b.HasKey("UserName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("aplicationProject.Models.Reviewing", b =>
                {
                    b.HasOne("aplicationProject.Models.Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("aplicationProject.Models.Review")
                        .WithMany("Movies")
                        .HasForeignKey("ReviewID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
